// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQuWA0BTa5RXnvCUPGrUhNt2u5h5qMD18',
    appId: '1:659142019462:android:61659a632631e2d481c407',
    messagingSenderId: '659142019462',
    projectId: 'buku-interaktif',
    databaseURL: 'https://buku-interaktif-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buku-interaktif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJOXQ5zW-KIelIL0rO5h5t8tRCQTwd1g',
    appId: '1:659142019462:ios:8a9acceebf16dcd481c407',
    messagingSenderId: '659142019462',
    projectId: 'buku-interaktif',
    databaseURL: 'https://buku-interaktif-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buku-interaktif.firebasestorage.app',
    iosBundleId: 'com.example.newLaris',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7UIrfJXrZL9P9efZxta0zme4xRv5oNL4',
    appId: '1:659142019462:web:186b01f7aff8ddbb81c407',
    messagingSenderId: '659142019462',
    projectId: 'buku-interaktif',
    authDomain: 'buku-interaktif.firebaseapp.com',
    databaseURL: 'https://buku-interaktif-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buku-interaktif.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJOXQ5zW-KIelIL0rO5h5t8tRCQTwd1g',
    appId: '1:659142019462:ios:8a9acceebf16dcd481c407',
    messagingSenderId: '659142019462',
    projectId: 'buku-interaktif',
    databaseURL: 'https://buku-interaktif-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buku-interaktif.firebasestorage.app',
    iosBundleId: 'com.example.newLaris',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHigolgPqn9XR2TxhjjC2TvJcqVAIlYnQ',
    appId: '1:659142019462:web:1145cebbf020177f81c407',
    messagingSenderId: '659142019462',
    projectId: 'buku-interaktif',
    authDomain: 'buku-interaktif.firebaseapp.com',
    databaseURL: 'https://buku-interaktif-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buku-interaktif.firebasestorage.app',
  );

}